### SEO, Analytics & 3rd-party
netlify_forms = true # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt

### Content
favicon = true # Enable favicon, add your favicon files to /static/ directory
avatar = 'avatar.png' # Custom avatar image in /assets/
grayscale_avatar = false # Add a grayscale filter to the avatar image
author = 'Vitor Marques' # Default author for <head> meta
description = "Blog pessoal e portfólio online do Vitor Marques" # Add a global meta description to <head>
footer_text = "Construído com **carinho**!" # Customize footer text
fallback_text = "Ainda sem conteúdo disponível. Em breve." # Fallback text for empty content
label_drafts = true # Add a label indicator next to the title of any built drafts (dev only)

# Customize newsletter text
newsletter_header = "Nunca perder uma novidade?"
newsletter_description = "Receba atualizações ocasionalmente sobre os meus projetos multimédia e descobre mais sobre o mundo criativo que me apaixona."
newsletter_submit = "Subscreve"
global_newsletter = true # Enable newsletter site-wide

# CSS / JavaScript
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing
custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors

### Web schemas
# Open Graph
images = ['images/default.png'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image.
ogLocale = "en_US" # Open graph locale

# Twitter Cards
twitterSite = "tiago815842" # Enter your twitter handle without the @
twitterCreator = "tiago815842" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaName = "John Doe" # Enter your name
schemaLocale = "en-US" # Structured data locale
schemaImage = "images/default.png" # Image for Person structured data schema. Enter path to the image.
schemaImageWidth = 453 # Width of the above image
schemaImageHeight = 455 # Height of the above image

### Social
# Show social links in footer, home hero section, or about page
footer_socials = true
home_hero_socials = true
about_page_socials = true

# Enable or disable individual social icons
[social.links]
  twitter = "tiago815842"
  github = "MiraiyGUNA"
  # stack_overflow = "userid/username" # include user id
  email = "miraiy2@protonmail.com"
  # linkedin = "username" # Comment out to disable
  # mastodon_server = "example.social" # include subdomains if relevant, scheme not needed (defaults to https)
  # mastodon_user = "username" # don't include preceding @

# Enable or disable individual social share icons in posts
[social.share]
  facebook = true
  linkedin = true
  twitter = true
  reddit = true
  email = true